name: abstract_bloc
description: Abstraction for fetching local or remote data via flutter_bloc
version: 2.2.2
repository: https://github.com/salihagic/abstract_bloc

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_bloc_event_bus: ^0.0.6
  rest_api_client: ^2.4.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0